language: nix

branches:
  only:
  - master

addons:
  ssh_known_hosts:
    - git.urbanslug.com

before_script:
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name  "$GIT_NAME"

script:
  - ./site.hs build

after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 travis-ci
  - ssh-add travis-ci
  - cd _site
  - git init
  - git remote add deploy "deploy@git.urbanslug.com:~/blog"
  - git add --all
  - git status
  - git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
  - git push --force -v deploy master:master

env:
  global:
    - NIX_PATH: nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/b7e4857dd906022e4f996ae13ccb2988f2782de0.tar.gz
    - GIT_EMAIL: travis@travis-ci.org
    - GIT_NAME: Travis CI

before_install:
  - openssl aes-256-cbc -K $encrypted_7f9f7befb56d_key -iv $encrypted_7f9f7befb56d_iv -in travis-ci.enc -out travis-ci -d
